<?php

/**
 * AsignaturasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AsignaturasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AsignaturasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Asignaturas');
    }
}