<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CiSessions', 'default');

/**
 * BaseCiSessions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $session_id
 * @property string $ip_address
 * @property string $user_agent
 * @property integer $last_activity
 * @property string $user_data
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCiSessions extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('ci_sessions');
        $this->hasColumn('session_id', 'string', 40, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => '40',
             ));
        $this->hasColumn('ip_address', 'string', 16, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '16',
             ));
        $this->hasColumn('user_agent', 'string', 120, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '120',
             ));
        $this->hasColumn('last_activity', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('user_data', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}