<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Titulaciones', 'default');

/**
 * Titulacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $codigo
 * @property string $nombre
 * @property integer $creditos
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     Daniel Ignacio Salazar Recio <danielsalazarrecio@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Titulacion extends Doctrine_Record
{
  public function setTableDefinition()
  {
    $this->setTableName('titulaciones');
    $this->hasColumn('id', 'integer', 4, array(
					       'type' => 'integer',
					       'length' => 4,
					       'primary' => true,
					       'autoincrement' => true,
					       'unsigned' => false,
					       'fixed' => false
					       ));
    $this->hasColumn('codigo', 'string', 4, array(
    					  'minlength' => 4,	
						  'length' => 4,
						  'notnull',
						  'notblank',						  
						  'unique',
						  'regexp' => '/[0-9]{4}/',
						  'unsigned' => false
						  ));
    $this->hasColumn('nombre', 'string', 200, array(
						    'type' => 'string',
						    'minlength' => 5,
						    'length' => 200,
						    'notnull' => true,
						    'unique' => true,
						    'notblank' => true,
						    'unsigned' => false
						    ));
    $this->hasColumn('creditos', 'integer', 4, array(
						     'type' => 'integer',
						     'length' => 4,
						     'unsigned' => true,
						     'notnull' => true,
						     'notblank' => true
						     ));
    $this->hasColumn('num_cursos', 'integer', 4, array(
                                'type' => 'integer',
                                'length' => 4,
                                'unsigned' => true,
                                'notnull' => true,
                                'notblank' => true
                             ));
  }

  public function getPlanificacion($id_curso)
  {
        $asignaturas = $this->asignaturas;
        $salida_total = array();
        foreach($asignaturas as $asignatura)
        {
            // Por cada asignatura consultamos su planificación docente para el curso dado
            $q = Doctrine_Query::create()->select('c.*, p.*, a.descripcion')
                    ->from('PlanActividad p')
                    ->innerJoin('p.plandocente c')
                    ->innerJoin('p.actividad a')
                    ->where('c.id_curso = ? AND c.id_asignatura = ?', array($id_curso, $asignatura->id));
            $resultado = $q->execute();
            $salida = array();
            $salida[0] =  $asignatura->nombre;
            // Vamos guardando en el vector salida una fila por actividad con el id dado
            foreach($resultado as $actividad)
            {
                $salida[$actividad->id_actividad] = array($actividad->horas, $actividad->grupos, $actividad->horas_semanales);
            }
            
            foreach(range(1,5) as $i){
                $salida[$i] = isset($salida[$i])? $salida[$i] : array(0,0,0);
            }
            // Guardamos en el vector final
            $salida_total[] = $salida;
      }

      return $salida_total;
  }
  
  public function setUp()
  {
    parent::setUp();
    $this->hasMany('Asignatura as asignaturas', array('local' => 'id', 'foreign' => 'titulacion_id', 'onDelete' => 'CASCADE'));
  }
}
