<?php

/**
 * TitulacionesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TitulacionesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TitulacionesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Titulaciones');
    }
}